name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Run workflow on version tags, e.g. v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
          
      - name: Build with Maven
        run: mvn clean package -DskipTests
        
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: AutomataViz ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            target/AutomataViz-*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 